fix: handle objective constant with gurobi
coin-or/python-mip pull request #214
Opened 2021-10-18 14:35 UTC by peterlietz

I added two unit tests that currently fail for gurobi along with the proposed fix.

2022-01-16 17:35 UTC, tuliotoffolo approved these changes

2022-01-16 19:21 UTC, tuliotoffolo requested changes
Thanks for the fix.
Would you please do `obj_expr.const = self.get_objective_const()` instead? The summation would result in the creation of a new LinExpr, which is unnecessary here.

2022-03-23 17:57 UTC, sebheger commented
@gdragotto I will do a short review in the next few days, but I think this is ready so far.

@peterlietz Would you squash the commits and give it a speaking name? Otherwise, I would do it.

2022-03-24 09:00 UTC, peterlietz commented
Hi @sebheger, I squashed the changes. Hope everything is fine.

2022-03-24 10:50 UTC, merged